joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

gripper_joint_position:
  type: effort_controllers/JointPositionController
  joint: gripper_joint
  pid: {p: 5.0, i: 0.0, d: 0.0}
