<?xml version="1.0"?>
<package format="3">
  <name>bprrt</name>
  <version>0.1.0</version>
  <description>BP-RRT* planner for UR3e</description>
  <maintainer email="you@your.email">Your Name</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tools -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_index_cpp</buildtool_depend>

  <!-- Core dependencies -->
  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>geometry_msgs</depend>
  <depend>gazebo_msgs</depend>
  <depend>moveit_core</depend>
  <depend>moveit_msgs</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>Eigen3</depend>
  <depend>tf2</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>Boost</depend>
  <depend>ament_index_cpp</depend>
  <depend>ros_gz_interfaces</depend>


  <!-- Launch-time (Python) dependencies -->
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>

  <!-- Lint / test -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
</package>
